<form action="/access-free-30-day-trial.php" method="post" class="has-validation-callback" id="formLayerAccess">
	<div class="sl-l-block">
		<input
			class="sl-e-input first flex-1"
			type="text"
			data-validation="required"
			name="name"
			id="name"
			placeholder="Name*"
		/>

		<input
			class="sl-e-input flex-1"
			type="text"
			data-validation="required"
			name="surname"
			id="surname"
			placeholder="Surname*"
		/>
	</div>

	<div class="sl-l-block">
		<input
			class="sl-e-input flex-1"
			type="text"
			data-validation="required"
			name="name"
			id="name"
			placeholder="Name*"
		/>
	</div>
	
	<button
		class="sl-e-button primary justify-center flex-1 w-100"
		type="submit"
		id="submit"
		name="action"
	>
		Start your free trial
	</button>

</form>
