<div class="sl-c-flex">
	<h1>Links</h1>
</div>

<div class="sl-c-flex" data-direction="row" data-padding="1">
	<div class="sl-c-flex-item" data-padding="1">
		<a class="sl-e-link" href="#">Link</a>
	</div>

	<div class="sl-c-flex-item" data-padding="1">
		<a class="sl-e-link" data-icon="arrow-right-green" href="#">Link</a>
	</div>
</div>

<div class="sl-c-flex" data-direction="row" data-padding="1">
	<div class="sl-c-flex-item" data-padding="1">
		<a class="sl-e-link" data-color="text" href="#">Link</a>
	</div>

	<div class="sl-c-flex-item" data-padding="1">
		<a class="sl-e-link" data-color="text" data-icon="arrow-right" href="#">
			Link
		</a>
	</div>
</div>
