<div class="sl-l-block py-5">
	<h1>Links</h1>
</div>

<div class="sl-l-block py-3 mb-4" >
	<div class="sl-l-block-item pr-3">
		<a class="sl-e-link" href="#">Link</a>
	</div>

	<div class="sl-l-block-item">
		<a class="sl-e-link" data-icon="arrow-right-green" href="#">Link</a>
	</div>
</div>

<div class="sl-l-block">
	<div class="sl-l-block-item pr-3">
		<a class="sl-e-link" data-color="text" href="#">Link</a>
	</div>

	<div class="sl-l-block-item">
		<a class="sl-e-link" data-color="text" data-icon="arrow-right" href="#">
			Link
		</a>
	</div>
</div>
