<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Sales Layer Design System - Playground</title>
	<script async src="./dist/index.bundle.js"></script>

	<link rel="stylesheet" href="./dist/index.min.css" />
	<link rel="stylesheet" href="https://use.typekit.net/yhp0ziy.css" />
</head>
