<nav class="nav block direction-row justify-between w-100 bg-white border-bottom">
	<div class="container w-100">


		<div class="block direction-row justify-between">
			<div class="block direction-row align-center px-5 py-3">
				<div class="pr-7">
					<a class="link" href="./index.php">
						<h3 class="color-primary">Barebones</h3>
					</a>
				</div>
				<div class="pr-5">
					<a
						class="link dropdown-trigger"
						data-dropdown_trigger="elements"
						href="#"
					>
						<span class="color-light">Elements</span>
						<i class="icon light ri-arrow-down-s-line"></i>
					</a>
					<div class="dropdown center" data-dropdown_name="elements">
						<div class="block w-100 direction-column">
							<div class="block w-100 hover-light">
								<a class="link p-3" href="blocks.php"><span class="color-text">Blocks</span></a>
							</div>
							<div class="block hover-light">
								<a class="link p-3 w-100" href="buttons.php"><span class="color-text">Buttons</span></a>
							</div>
							<div class="block hover-light">
								<a class="link p-3 w-100" href="links.php"><span class="color-text">Links</span></a>
							</div>
						</div>
					</div>
				</div>

				<div class="pr-5">
					<a class="link dropdown-trigger" data-dropdown_trigger="components" href="#">
						<span class="color-light">Components</span>
						<i class="icon light ri-arrow-down-s-line"></i>
					</a>
					<div class="dropdown" data-dropdown_name="components">
						<div class="block w-100 direction-column">
							<div class="block w-100 hover-light">
								<a class="link p-3" href="dropdowns.php"><span class="color-text">Dropdowns</span></a>
							</div>
							<div class="block w-100 hover-light">
								<a class="link p-3" href="toasts.php"><span class="color-text">Toasts</span></a>
							</div>
							<div class="block w-100 hover-light">
								<a class="link p-3" href="alerts.php"><span class="color-text">Alerts</span></a>
							</div>
							<div class="block w-100 hover-light">
								<a class="link p-3" href="modals.php"><span class="color-text">Modals</span></a>
							</div>
							<div class="block w-100 hover-light">
								<a class="link p-3" href="tags.php"><span class="color-text">Tag</span></a>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="block direction-row align-center px-5 py-3">
				<a href="https://github.com/wimogas/barebones-framework" target="_blank">
					<button class="button primary small">Github</button>
				</a>
			</div>
		</div>
		
	</div>
</nav>
