<nav class="sl-l-block p-3" data-justify="between" data-background="dark">
	<ul class="sl-l-block">
		<li class="pr-5">
			<a href="./index.php">
				<h3 data-color="white">SL DESIGN SYSTEM</h3>
			</a>
		</li>
		<li class="pr-5">
			<a
				class="sl-js-dropdown"
				data-dropdown_name="elements"
				data-color="light"
				data-icon="arrow"
				href="#"
			>
				Elements
			</a>
			<div class="sl-c-dropdown-menu" data-dropdown_parent="elements">
				<ul>
					<li data-hover="light">
						<a class="p-3 w-100" data-color="text" href="links.php">Links</a>
					</li>
					<li data-hover="light">
						<a class="p-3 w-100" data-color="text" href="buttons.php"
							>Buttons</a
						>
					</li>
				</ul>
			</div>
		</li>

		<li class="pr-5">
			<a
				class="sl-js-dropdown"
				data-dropdown_name="components"
				data-color="light"
				data-icon="arrow"
				href="#"
			>
				Components
			</a>
			<div class="sl-c-dropdown-menu" data-dropdown_parent="components">
				<ul>
					<li data-hover="light">
						<a class="p-3 w-100" data-color="text" href="dropdowns.php"
							>Dropdowns</a
						>
					</li>
				</ul>
			</div>
		</li>
	</ul>
</nav>
