<nav class="sl-c-nav sl-l-block p-3 justify-between w-100 bg-dark">
	<ul class="sl-l-block">
		<li class="pr-5">
			<a href="./index.php">
				<h3 class="color-white">SL DESIGN SYSTEM</h3>
			</a>
		</li>
		<li class="pr-5">
			<a
				class="sl-js-dropdown color-light"
				data-dropdown_name="elements"
				href="#"
			>
				Elements
				<i class="icon medium ml-2">
					<img src="./assets/icons/arrow.svg" />
				</i>
			</a>
			<div class="sl-c-dropdown-menu center" data-dropdown_parent="elements">
				<ul>
					<li class="hover-light">
						<a class="p-3 w-100 color-text" href="links.php">Links</a>
					</li>
					<li class="hover-light">
						<a class="p-3 w-100 color-text" href="buttons.php">Buttons</a>
					</li>
				</ul>
			</div>
		</li>

		<li class="pr-5">
			<a
				class="sl-js-dropdown color-light"
				data-dropdown_name="components"
				href="#"
			>
				Components
				<i class="icon medium ml-2">
					<img src="./assets/icons/arrow.svg" />
				</i>
			</a>
			<div class="sl-c-dropdown-menu" data-dropdown_parent="components">
				<ul>
					<li class="hover-light">
						<a class="p-3 w-100 color-text" href="dropdowns.php">Dropdowns</a>
					</li>
					<li class="hover-light">
						<a class="p-3 w-100 color-text" href="dam.php">DAM</a>
					</li>
				</ul>
			</div>
		</li>
	</ul>
</nav>
