<nav class="sl-c-nav" data-background="dark" data-variant="sidenav">

  <ul class="sl-c-list">
    <li class="sl-c-list-item">
    <a 
      class="sl-e-link" 
      href="#">
        <h3 data-color="white"><a class="sl-e-link" href="index.php">SL DESIGN SYSTEM</a></h3>
    </a>
    </li>
    <li class="sl-c-list-item">
      <a 
        class="sl-e-link sl-c-dropdown" 
        data-dropdown_id="el1" 
        data-color="light" 
        data-icon="arrow" 
        href="#">
          Elements
      </a>
      <div 
        class="sl-c-dropdown-menu" 
        data-dropdown_toggler="el1">
          <ul class="sl-c-list" 
            data-variant="condensed"
            data-align="left">
            <li class="sl-c-list-item">
              <a class="sl-e-link" 
                data-color="text" 
                href="links.php">Links</a>
            </li>
            <li class="sl-c-list-item">
              <a class="sl-e-link" 
                data-color="text" 
                href="buttons.php">Buttons</a>
            </li>
          </ul> 
      </div>
    </li>

    <li class="sl-c-list-item">
      <a 
        class="sl-e-link sl-c-dropdown" 
        data-dropdown_id="el2" 
        data-color="light" 
        data-icon="arrow" 
        href="#">
          Components
      </a>
      <div 
        class="sl-c-dropdown-menu" 
        data-dropdown_toggler="el2">
          <ul class="sl-c-list"
            data-variant="condensed"
            data-align="left">
            <li class="sl-c-list-item">
              <a class="sl-e-link" 
                data-color="text" 
                href="dropdowns.php">Dropdowns</a>
            </li>
          </ul> 
      </div>
    </li>
  </ul>

  <ul class="sl-c-list">
    <li class="sl-c-list-item">
      <a 
        class="sl-e-link" 
        data-color="light" 
        href="#">
          Documentation
      </a>
      
    </li>

    <li class="sl-c-list-item">
      <a 
        class="sl-e-link" 
        data-color="light" 
        href="#">
          Github
      </a>
     
    </li>
  </ul>
  
</nav>