<div class="sl-c-tree-panel" data-border="normal-right">

    <div class="sl-l-block" data-direction="column" data-align="start">

        <div class="sl-l-block p-3" data-justify="between" data-width="100">
            <h3>Folders<H3>
            <a class="icon medium" href="#">
			    <?php include './assets/icons/add.svg' ?>
		    </a>
        </div>


        <div class="sl-l-block" data-justify="between" data-width="100">

            <div class="sl-c-folder-block sl-l-block py-2" style="padding-left: 16px" data-hover="light" data-width="100">
                <div class="sl-l-block" data-grow="1">
                    <div class="sl-c-folder-name">
                        <div class="sl-l-block">
                            <a class="sl-c-folder-name--arrow mr-2" href="#">
                                <i class="icon medium">
                                    <?php include './assets/icons/arrow2.svg' ?>
                                </i>
                            </a>
                            <a href="#">
                                <i class="sl-c-folder-name--icon icon medium mr-1">
                                    <?php include './assets/icons/folder-close.svg' ?>
                                </i>
                                <span class="sl-c-folder-name--text" data-color="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque turpis erat, consequat vitae ultrices egestas, fringilla vel sapien.</span>
                            </a>
                        </div>
                    
                    </div>
                </div>  
                <div class="sl-c-folder-menu sl-c-block pr-3">
                    <a 
                        class="sl-c-folder-menu--toggler icon medium sl-js-dropdown" 
                        href="#" 
                        data-dropdown_name="folderMenu2" 
                        data-dropdown_align="center">
                        <?php include './assets/icons/more.svg' ?>
                    </a>
                    <div class="sl-c-dropdown-menu" data-dropdown_parent="folderMenu2">
                        <ul>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 1</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 2</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 3</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="sl-c-folder-block sl-l-block py-2" style="padding-left: 32px" data-hover="light" data-width="100">
                <div class="sl-l-block" data-grow="1">
                    <div class="sl-c-folder-name">
                        <div class="sl-l-block">
                            <a class="sl-c-folder-name--arrow mr-2" href="#">
                                <i class="icon medium">
                                    <?php include './assets/icons/arrow2.svg' ?>
                                </i>
                            </a>
                            <a href="#">
                                <i class="sl-c-folder-name--icon icon medium mr-1">
                                    <?php include './assets/icons/folder-close.svg' ?>
                                </i>
                                <span class="sl-c-folder-name--text" data-color="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque turpis erat, consequat vitae ultrices egestas, fringilla vel sapien.</span>
                            </a>
                        </div>
                    
                    </div>
                </div>  
                <div class="sl-c-folder-menu sl-c-block pr-3">
                    <a 
                        class="sl-c-folder-menu--toggler icon medium sl-js-dropdown" 
                        href="#" 
                        data-dropdown_name="folderMenu3" 
                        data-dropdown_align="center">
                        <?php include './assets/icons/more.svg' ?>
                    </a>
                    <div class="sl-c-dropdown-menu" data-dropdown_parent="folderMenu3">
                        <ul>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 1</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 2</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 3</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="sl-c-folder-block sl-l-block py-2" style="padding-left: 48px" data-hover="light" data-width="100">
                <div class="sl-l-block" data-grow="1">
                    <div class="sl-c-folder-name">
                        <div class="sl-l-block">
                            <a class="sl-c-folder-name--arrow mr-2" href="#">
                                <i class="icon medium">
                                    <?php include './assets/icons/arrow2.svg' ?>
                                </i>
                            </a>
                            <a href="#">
                                <i class="sl-c-folder-name--icon icon medium mr-1">
                                    <?php include './assets/icons/folder-close.svg' ?>
                                </i>
                                <span class="sl-c-folder-name--text" data-color="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque turpis erat, consequat vitae ultrices egestas, fringilla vel sapien.</span>
                            </a>
                        </div>
                    
                    </div>
                </div>  
                <div class="sl-c-folder-menu sl-c-block pr-3">
                    <a 
                        class="sl-c-folder-menu--toggler icon medium sl-js-dropdown" 
                        href="#" 
                        data-dropdown_name="folderMenu4" 
                        data-dropdown_align="center">
                        <?php include './assets/icons/more.svg' ?>
                    </a>
                    <div class="sl-c-dropdown-menu" data-dropdown_parent="folderMenu4">
                        <ul>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 1</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 2</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 3</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="sl-c-folder-block sl-c-folder-block--active sl-l-block py-2" style="padding-left: 16px" data-hover="light" data-width="100">
                <div class="sl-l-block" data-grow="1">
                    <div class="sl-c-folder-name">
                        <div class="sl-l-block">
                            <a class="sl-c-folder-name--arrow mr-2" href="#">
                                <i class="icon medium">
                                    <?php include './assets/icons/arrow2.svg' ?>
                                </i>
                            </a>
                            <a href="#">
                                <i class="sl-c-folder-name--icon icon medium mr-1">
                                    <?php include './assets/icons/folder-open.svg' ?>
                                </i>
                                <span class="sl-c-folder-name--text" data-color="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque turpis erat, consequat vitae ultrices egestas, fringilla vel sapien.</span>
                            </a>
                        </div>
                    
                    </div>
                </div>  
                <div class="sl-c-folder-menu sl-c-block pr-3">
                    <a 
                        class="sl-c-folder-menu--toggler icon medium sl-js-dropdown" 
                        href="#" 
                        data-dropdown_name="folderMenu5" 
                        data-dropdown_align="center">
                        <?php include './assets/icons/more.svg' ?>
                    </a>
                    <div class="sl-c-dropdown-menu" data-dropdown_parent="folderMenu5">
                        <ul>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 1</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 2</a>
                            </li>
                            <li data-hover="light">
                                <a class="p-3" data-width="100" href="#">Item 3</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>



        </div>


    </div>
</div>
